import React, { Component } from "react";
import "./App.css";
import FilteredList from "./FilteredList";

// This is the list of dictionaries of people who voted on the equality act
// we got this through the code at the bottom, but found it easier and
// clearer to copy it in.
const people = [
{us_state: "GA", vote: "Yes", party: "Democrat", name: "Rep. Sanford Bishop Jr. [D]", img: "https://www.govtrack.us/static/legislator-photos/400030-200px.jpeg", fav: false },
{us_state: "OR", vote: "Yes", party: "Democrat", name: "Rep. Earl Blumenauer [D]", img: "https://www.govtrack.us/static/legislator-photos/400033-200px.jpeg", fav: false },
{us_state: "HI", vote: "Yes", party: "Democrat", name: "Rep. Ed Case [D]", img: "https://www.govtrack.us/static/legislator-photos/400069-200px.jpeg", fav: false },
{us_state: "MO", vote: "Yes", party: "Democrat", name: "Rep. Lacy Clay Jr. [D]", img: "https://www.govtrack.us/static/legislator-photos/400074-200px.jpeg", fav: false },
{us_state: "SC", vote: "Abstained", party: "Democrat", name: "Rep. James “Jim” Clyburn [D]", img: "https://www.govtrack.us/static/legislator-photos/400075-200px.jpeg", fav: false },
{us_state: "TN", vote: "Yes", party: "Democrat", name: "Rep. Jim Cooper [D]", img: "https://www.govtrack.us/static/legislator-photos/400081-200px.jpeg", fav: false },
{us_state: "MD", vote: "Yes", party: "Democrat", name: "Rep. Elijah Cummings [D]", img: "https://www.govtrack.us/static/legislator-photos/400090-200px.jpeg", fav: false },
{us_state: "IL", vote: "Yes", party: "Democrat", name: "Rep. Danny Davis [D]", img: "https://www.govtrack.us/static/legislator-photos/400093-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Susan Davis [D]", img: "https://www.govtrack.us/static/legislator-photos/400097-200px.jpeg", fav: false },
{us_state: "OR", vote: "Yes", party: "Democrat", name: "Rep. Peter DeFazio [D]", img: "https://www.govtrack.us/static/legislator-photos/400100-200px.jpeg", fav: false },
{us_state: "CO", vote: "Yes", party: "Democrat", name: "Rep. Diana DeGette [D]", img: "https://www.govtrack.us/static/legislator-photos/400101-200px.jpeg", fav: false },
{us_state: "CT", vote: "Yes", party: "Democrat", name: "Rep. Rosa DeLauro [D]", img: "https://www.govtrack.us/static/legislator-photos/400103-200px.jpeg", fav: false },
{us_state: "TX", vote: "Yes", party: "Democrat", name: "Rep. Lloyd Doggett [D]", img: "https://www.govtrack.us/static/legislator-photos/400111-200px.jpeg", fav: false },
{us_state: "PA", vote: "Yes", party: "Democrat", name: "Rep. Michael “Mike” Doyle Jr. [D]", img: "https://www.govtrack.us/static/legislator-photos/400114-200px.jpeg", fav: false },
{us_state: "NY", vote: "Yes", party: "Democrat", name: "Rep. Eliot Engel [D]", img: "https://www.govtrack.us/static/legislator-photos/400122-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Anna Eshoo [D]", img: "https://www.govtrack.us/static/legislator-photos/400124-200px.jpeg", fav: false },
{us_state: "AZ", vote: "Yes", party: "Democrat", name: "Rep. Raúl Grijalva [D]", img: "https://www.govtrack.us/static/legislator-photos/400162-200px.jpeg", fav: false },
{us_state: "FL", vote: "Yes", party: "Democrat", name: "Rep. Alcee Hastings [D]", img: "https://www.govtrack.us/static/legislator-photos/400170-200px.jpeg", fav: false },
{us_state: "MD", vote: "Yes", party: "Democrat", name: "Rep. Steny Hoyer [D]", img: "https://www.govtrack.us/static/legislator-photos/400189-200px.jpeg", fav: false },
{us_state: "TX", vote: "Yes", party: "Democrat", name: "Rep. Sheila Jackson Lee [D]", img: "https://www.govtrack.us/static/legislator-photos/400199-200px.jpeg", fav: false },
{us_state: "TX", vote: "Yes", party: "Democrat", name: "Rep. Eddie Johnson [D]", img: "https://www.govtrack.us/static/legislator-photos/400204-200px.jpeg", fav: false },
{us_state: "OH", vote: "Yes", party: "Democrat", name: "Rep. Marcy Kaptur [D]", img: "https://www.govtrack.us/static/legislator-photos/400211-200px.jpeg", fav: false },
{us_state: "WI", vote: "Yes", party: "Democrat", name: "Rep. Ron Kind [D]", img: "https://www.govtrack.us/static/legislator-photos/400218-200px.jpeg", fav: false },
{us_state: "RI", vote: "Yes", party: "Democrat", name: "Rep. James “Jim” Langevin [D]", img: "https://www.govtrack.us/static/legislator-photos/400230-200px.jpeg", fav: false },
{us_state: "WA", vote: "Yes", party: "Democrat", name: "Rep. Rick Larsen [D]", img: "https://www.govtrack.us/static/legislator-photos/400232-200px.jpeg", fav: false },
{us_state: "CT", vote: "Yes", party: "Democrat", name: "Rep. John Larson [D]", img: "https://www.govtrack.us/static/legislator-photos/400233-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Barbara Lee [D]", img: "https://www.govtrack.us/static/legislator-photos/400237-200px.jpeg", fav: false },
{us_state: "GA", vote: "Yes", party: "Democrat", name: "Rep. John Lewis [D]", img: "https://www.govtrack.us/static/legislator-photos/400240-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Zoe Lofgren [D]", img: "https://www.govtrack.us/static/legislator-photos/400245-200px.jpeg", fav: false },
{us_state: "NY", vote: "Yes", party: "Democrat", name: "Rep. Nita Lowey [D]", img: "https://www.govtrack.us/static/legislator-photos/400246-200px.jpeg", fav: false },
{us_state: "MA", vote: "Yes", party: "Democrat", name: "Rep. Stephen Lynch [D]", img: "https://www.govtrack.us/static/legislator-photos/400249-200px.jpeg", fav: false },
{us_state: "NY", vote: "Yes", party: "Democrat", name: "Rep. Carolyn Maloney [D]", img: "https://www.govtrack.us/static/legislator-photos/400251-200px.jpeg", fav: false },
{us_state: "MN", vote: "Yes", party: "Democrat", name: "Rep. Betty McCollum [D]", img: "https://www.govtrack.us/static/legislator-photos/400259-200px.jpeg", fav: false },
{us_state: "MA", vote: "Yes", party: "Democrat", name: "Rep. James “Jim” McGovern [D]", img: "https://www.govtrack.us/static/legislator-photos/400263-200px.jpeg", fav: false },
{us_state: "NY", vote: "Yes", party: "Democrat", name: "Rep. Gregory Meeks [D]", img: "https://www.govtrack.us/static/legislator-photos/400271-200px.jpeg", fav: false },
{us_state: "NY", vote: "Yes", party: "Democrat", name: "Rep. Jerrold Nadler [D]", img: "https://www.govtrack.us/static/legislator-photos/400289-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Grace Napolitano [D]", img: "https://www.govtrack.us/static/legislator-photos/400290-200px.jpeg", fav: false },
{us_state: "MA", vote: "Yes", party: "Democrat", name: "Rep. Richard Neal [D]", img: "https://www.govtrack.us/static/legislator-photos/400291-200px.jpeg", fav: false },
{us_state: "NJ", vote: "Yes", party: "Democrat", name: "Rep. Frank Pallone Jr. [D]", img: "https://www.govtrack.us/static/legislator-photos/400308-200px.jpeg", fav: false },
{us_state: "NJ", vote: "Yes", party: "Democrat", name: "Rep. Bill Pascrell Jr. [D]", img: "https://www.govtrack.us/static/legislator-photos/400309-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Nancy Pelosi [D]", img: "https://www.govtrack.us/static/legislator-photos/400314-200px.jpeg", fav: false },
{us_state: "MN", vote: "Abstained", party: "Democrat", name: "Rep. Collin Peterson [D]", img: "https://www.govtrack.us/static/legislator-photos/400316-200px.jpeg", fav: false },
{us_state: "NC", vote: "Yes", party: "Democrat", name: "Rep. David Price [D]", img: "https://www.govtrack.us/static/legislator-photos/400326-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Lucille Roybal-Allard [D]", img: "https://www.govtrack.us/static/legislator-photos/400347-200px.jpeg", fav: false },
{us_state: "MD", vote: "Yes", party: "Democrat", name: "Rep. A. Dutch Ruppersberger [D]", img: "https://www.govtrack.us/static/legislator-photos/400349-200px.jpeg", fav: false },
{us_state: "IL", vote: "Yes", party: "Democrat", name: "Rep. Bobby Rush [D]", img: "https://www.govtrack.us/static/legislator-photos/400350-200px.jpeg", fav: false },
{us_state: "OH", vote: "Abstained", party: "Democrat", name: "Rep. Tim Ryan [D]", img: "https://www.govtrack.us/static/legislator-photos/400352-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Linda Sánchez [D]", img: "https://www.govtrack.us/static/legislator-photos/400355-200px.jpeg", fav: false },
{us_state: "IL", vote: "Yes", party: "Democrat", name: "Rep. Janice “Jan” Schakowsky [D]", img: "https://www.govtrack.us/static/legislator-photos/400360-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Adam Schiff [D]", img: "https://www.govtrack.us/static/legislator-photos/400361-200px.jpeg", fav: false },
{us_state: "GA", vote: "Yes", party: "Democrat", name: "Rep. David Scott [D]", img: "https://www.govtrack.us/static/legislator-photos/400363-200px.jpeg", fav: false },
{us_state: "VA", vote: "Yes", party: "Democrat", name: "Rep. Robert “Bobby” Scott [D]", img: "https://www.govtrack.us/static/legislator-photos/400364-200px.jpeg", fav: false },
{us_state: "NY", vote: "Yes", party: "Democrat", name: "Rep. José Serrano [D]", img: "https://www.govtrack.us/static/legislator-photos/400366-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Brad Sherman [D]", img: "https://www.govtrack.us/static/legislator-photos/400371-200px.jpeg", fav: false },
{us_state: "WA", vote: "Yes", party: "Democrat", name: "Rep. Adam Smith [D]", img: "https://www.govtrack.us/static/legislator-photos/400379-200px.jpeg", fav: false },
{us_state: "MS", vote: "Yes", party: "Democrat", name: "Rep. Bennie Thompson [D]", img: "https://www.govtrack.us/static/legislator-photos/400402-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Mike Thompson [D]", img: "https://www.govtrack.us/static/legislator-photos/400403-200px.jpeg", fav: false },
{us_state: "NY", vote: "Yes", party: "Democrat", name: "Rep. Nydia Velázquez [D]", img: "https://www.govtrack.us/static/legislator-photos/400416-200px.jpeg", fav: false },
{us_state: "IN", vote: "Yes", party: "Democrat", name: "Rep. Peter Visclosky [D]", img: "https://www.govtrack.us/static/legislator-photos/400417-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Maxine Waters [D]", img: "https://www.govtrack.us/static/legislator-photos/400422-200px.jpeg", fav: false },
{us_state: "NC", vote: "Yes", party: "Democrat", name: "Rep. George “G.K.” Butterfield Jr. [D]", img: "https://www.govtrack.us/static/legislator-photos/400616-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Jim Costa [D]", img: "https://www.govtrack.us/static/legislator-photos/400618-200px.jpeg", fav: false },
{us_state: "FL", vote: "Yes", party: "Democrat", name: "Rep. Debbie Wasserman Schultz [D]", img: "https://www.govtrack.us/static/legislator-photos/400623-200px.jpeg", fav: false },
{us_state: "IL", vote: "Yes", party: "Democrat", name: "Rep. Daniel Lipinski [D]", img: "https://www.govtrack.us/static/legislator-photos/400630-200px.jpeg", fav: false },
{us_state: "MO", vote: "Yes", party: "Democrat", name: "Rep. Emanuel Cleaver II [D]", img: "https://www.govtrack.us/static/legislator-photos/400639-200px.jpeg", fav: false },
{us_state: "NY", vote: "Yes", party: "Democrat", name: "Rep. Brian Higgins [D]", img: "https://www.govtrack.us/static/legislator-photos/400641-200px.jpeg", fav: false },
{us_state: "TX", vote: "Yes", party: "Democrat", name: "Rep. Al Green [D]", img: "https://www.govtrack.us/static/legislator-photos/400653-200px.jpeg", fav: false },
{us_state: "TX", vote: "Yes", party: "Democrat", name: "Rep. Henry Cuellar [D]", img: "https://www.govtrack.us/static/legislator-photos/400657-200px.jpeg", fav: false },
{us_state: "WI", vote: "Yes", party: "Democrat", name: "Rep. Gwen Moore [D]", img: "https://www.govtrack.us/static/legislator-photos/400661-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Doris Matsui [D]", img: "https://www.govtrack.us/static/legislator-photos/400663-200px.jpeg", fav: false },
{us_state: "NJ", vote: "Yes", party: "Democrat", name: "Rep. Albio Sires [D]", img: "https://www.govtrack.us/static/legislator-photos/412186-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Jerry McNerney [D]", img: "https://www.govtrack.us/static/legislator-photos/412189-200px.jpeg", fav: false },
{us_state: "CO", vote: "Yes", party: "Democrat", name: "Rep. Ed Perlmutter [D]", img: "https://www.govtrack.us/static/legislator-photos/412192-200px.jpeg", fav: false },
{us_state: "CT", vote: "Yes", party: "Democrat", name: "Rep. Joe Courtney [D]", img: "https://www.govtrack.us/static/legislator-photos/412193-200px.jpeg", fav: false },
{us_state: "FL", vote: "Yes", party: "Democrat", name: "Rep. Kathy Castor [D]", img: "https://www.govtrack.us/static/legislator-photos/412195-200px.jpeg", fav: false },
{us_state: "GA", vote: "Yes", party: "Democrat", name: "Rep. Henry “Hank” Johnson Jr. [D]", img: "https://www.govtrack.us/static/legislator-photos/412199-200px.jpeg", fav: false },
{us_state: "IA", vote: "Yes", party: "Democrat", name: "Rep. David Loebsack [D]", img: "https://www.govtrack.us/static/legislator-photos/412209-200px.jpeg", fav: false },
{us_state: "KY", vote: "Yes", party: "Democrat", name: "Rep. John Yarmuth [D]", img: "https://www.govtrack.us/static/legislator-photos/412211-200px.jpeg", fav: false },
{us_state: "MD", vote: "Yes", party: "Democrat", name: "Rep. John Sarbanes [D]", img: "https://www.govtrack.us/static/legislator-photos/412212-200px.jpeg", fav: false },
{us_state: "NY", vote: "Yes", party: "Democrat", name: "Rep. Yvette Clarke [D]", img: "https://www.govtrack.us/static/legislator-photos/412221-200px.jpeg", fav: false },
{us_state: "TN", vote: "Yes", party: "Democrat", name: "Rep. Steve Cohen [D]", img: "https://www.govtrack.us/static/legislator-photos/412236-200px.jpeg", fav: false },
{us_state: "VT", vote: "Yes", party: "Democrat", name: "Rep. Peter Welch [D]", img: "https://www.govtrack.us/static/legislator-photos/412239-200px.jpeg", fav: false },
{us_state: "IL", vote: "Yes", party: "Democrat", name: "Rep. Bill Foster [D]", img: "https://www.govtrack.us/static/legislator-photos/412257-200px.jpeg", fav: false },
{us_state: "IN", vote: "Yes", party: "Democrat", name: "Rep. André Carson [D]", img: "https://www.govtrack.us/static/legislator-photos/412258-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Jackie Speier [D]", img: "https://www.govtrack.us/static/legislator-photos/412259-200px.jpeg", fav: false },
{us_state: "VA", vote: "Yes", party: "Democrat", name: "Rep. Gerald Connolly [D]", img: "https://www.govtrack.us/static/legislator-photos/412272-200px.jpeg", fav: false },
{us_state: "CT", vote: "Yes", party: "Democrat", name: "Rep. James Himes [D]", img: "https://www.govtrack.us/static/legislator-photos/412282-200px.jpeg", fav: false },
{us_state: "AZ", vote: "Yes", party: "Democrat", name: "Rep. Ann Kirkpatrick [D]", img: "https://www.govtrack.us/static/legislator-photos/412286-200px.jpeg", fav: false },
{us_state: "NM", vote: "Yes", party: "Democrat", name: "Rep. Ben Luján [D]", img: "https://www.govtrack.us/static/legislator-photos/412293-200px.jpeg", fav: false },
{us_state: "ME", vote: "Yes", party: "Democrat", name: "Rep. Chellie Pingree [D]", img: "https://www.govtrack.us/static/legislator-photos/412307-200px.jpeg", fav: false },
{us_state: "OR", vote: "Yes", party: "Democrat", name: "Rep. Kurt Schrader [D]", img: "https://www.govtrack.us/static/legislator-photos/412315-200px.jpeg", fav: false },
{us_state: "NV", vote: "Yes", party: "Democrat", name: "Rep. Dina Titus [D]", img: "https://www.govtrack.us/static/legislator-photos/412318-200px.jpeg", fav: false },
{us_state: "NY", vote: "Yes", party: "Democrat", name: "Rep. Paul Tonko [D]", img: "https://www.govtrack.us/static/legislator-photos/412319-200px.jpeg", fav: false },
{us_state: "OH", vote: "Yes", party: "Democrat", name: "Rep. Marcia Fudge [D]", img: "https://www.govtrack.us/static/legislator-photos/412327-200px.jpeg", fav: false },
{us_state: "IL", vote: "Yes", party: "Democrat", name: "Rep. Mike Quigley [D]", img: "https://www.govtrack.us/static/legislator-photos/412331-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Judy Chu [D]", img: "https://www.govtrack.us/static/legislator-photos/412379-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. John Garamendi [D]", img: "https://www.govtrack.us/static/legislator-photos/412382-200px.jpeg", fav: false },
{us_state: "FL", vote: "Yes", party: "Democrat", name: "Rep. Theodore Deutch [D]", img: "https://www.govtrack.us/static/legislator-photos/412385-200px.jpeg", fav: false },
{us_state: "AL", vote: "Yes", party: "Democrat", name: "Rep. Terri Sewell [D]", img: "https://www.govtrack.us/static/legislator-photos/412396-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Karen Bass [D]", img: "https://www.govtrack.us/static/legislator-photos/412404-200px.jpeg", fav: false },
{us_state: "FL", vote: "Yes", party: "Democrat", name: "Rep. Frederica Wilson [D]", img: "https://www.govtrack.us/static/legislator-photos/412412-200px.jpeg", fav: false },
{us_state: "LA", vote: "Yes", party: "Democrat", name: "Rep. Cedric Richmond [D]", img: "https://www.govtrack.us/static/legislator-photos/412432-200px.jpeg", fav: false },
{us_state: "MA", vote: "Yes", party: "Democrat", name: "Rep. William Keating [D]", img: "https://www.govtrack.us/static/legislator-photos/412435-200px.jpeg", fav: false },
{us_state: "RI", vote: "Yes", party: "Democrat", name: "Rep. David Cicilline [D]", img: "https://www.govtrack.us/static/legislator-photos/412470-200px.jpeg", fav: false },
{us_state: "OR", vote: "Yes", party: "Democrat", name: "Rep. Suzanne Bonamici [D]", img: "https://www.govtrack.us/static/legislator-photos/412501-200px.jpeg", fav: false },
{us_state: "WA", vote: "Yes", party: "Democrat", name: "Rep. Suzan DelBene [D]", img: "https://www.govtrack.us/static/legislator-photos/412505-200px.jpeg", fav: false },
{us_state: "NJ", vote: "Yes", party: "Democrat", name: "Rep. Donald Payne Jr. [D]", img: "https://www.govtrack.us/static/legislator-photos/412506-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Jared Huffman [D]", img: "https://www.govtrack.us/static/legislator-photos/412511-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Ami Bera [D]", img: "https://www.govtrack.us/static/legislator-photos/412512-200px.jpeg", fav: false },
{us_state: "CA", vote: "Abstained", party: "Democrat", name: "Rep. Eric Swalwell [D]", img: "https://www.govtrack.us/static/legislator-photos/412514-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Julia Brownley [D]", img: "https://www.govtrack.us/static/legislator-photos/412516-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Tony Cárdenas [D]", img: "https://www.govtrack.us/static/legislator-photos/412517-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Raul Ruiz [D]", img: "https://www.govtrack.us/static/legislator-photos/412519-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Mark Takano [D]", img: "https://www.govtrack.us/static/legislator-photos/412520-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Alan Lowenthal [D]", img: "https://www.govtrack.us/static/legislator-photos/412521-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Juan Vargas [D]", img: "https://www.govtrack.us/static/legislator-photos/412522-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Scott Peters [D]", img: "https://www.govtrack.us/static/legislator-photos/412523-200px.jpeg", fav: false },
{us_state: "FL", vote: "Yes", party: "Democrat", name: "Rep. Lois Frankel [D]", img: "https://www.govtrack.us/static/legislator-photos/412529-200px.jpeg", fav: false },
{us_state: "HI", vote: "Yes", party: "Democrat", name: "Rep. Tulsi Gabbard [D]", img: "https://www.govtrack.us/static/legislator-photos/412532-200px.jpeg", fav: false },
{us_state: "IL", vote: "Yes", party: "Democrat", name: "Rep. Bradley Schneider [D]", img: "https://www.govtrack.us/static/legislator-photos/412534-200px.jpeg", fav: false },
{us_state: "IL", vote: "Yes", party: "Democrat", name: "Rep. Cheri Bustos [D]", img: "https://www.govtrack.us/static/legislator-photos/412537-200px.jpeg", fav: false },
{us_state: "MA", vote: "Yes", party: "Democrat", name: "Rep. Joseph Kennedy III [D]", img: "https://www.govtrack.us/static/legislator-photos/412543-200px.jpeg", fav: false },
{us_state: "MI", vote: "Yes", party: "Democrat", name: "Rep. Daniel Kildee [D]", img: "https://www.govtrack.us/static/legislator-photos/412546-200px.jpeg", fav: false },
{us_state: "NH", vote: "Yes", party: "Democrat", name: "Rep. Ann Kuster [D]", img: "https://www.govtrack.us/static/legislator-photos/412557-200px.jpeg", fav: false },
{us_state: "NV", vote: "Yes", party: "Democrat", name: "Rep. Steven Horsford [D]", img: "https://www.govtrack.us/static/legislator-photos/412559-200px.jpeg", fav: false },
{us_state: "NY", vote: "Yes", party: "Democrat", name: "Rep. Grace Meng [D]", img: "https://www.govtrack.us/static/legislator-photos/412560-200px.jpeg", fav: false },
{us_state: "NY", vote: "Yes", party: "Democrat", name: "Rep. Hakeem Jeffries [D]", img: "https://www.govtrack.us/static/legislator-photos/412561-200px.jpeg", fav: false },
{us_state: "NY", vote: "Yes", party: "Democrat", name: "Rep. Sean Maloney [D]", img: "https://www.govtrack.us/static/legislator-photos/412562-200px.jpeg", fav: false },
{us_state: "OH", vote: "Yes", party: "Democrat", name: "Rep. Joyce Beatty [D]", img: "https://www.govtrack.us/static/legislator-photos/412565-200px.jpeg", fav: false },
{us_state: "PA", vote: "Yes", party: "Democrat", name: "Rep. Matthew Cartwright [D]", img: "https://www.govtrack.us/static/legislator-photos/412571-200px.jpeg", fav: false },
{us_state: "TX", vote: "Yes", party: "Democrat", name: "Rep. Joaquin Castro [D]", img: "https://www.govtrack.us/static/legislator-photos/412576-200px.jpeg", fav: false },
{us_state: "TX", vote: "Yes", party: "Democrat", name: "Rep. Marc Veasey [D]", img: "https://www.govtrack.us/static/legislator-photos/412579-200px.jpeg", fav: false },
{us_state: "TX", vote: "Yes", party: "Democrat", name: "Rep. Filemon Vela [D]", img: "https://www.govtrack.us/static/legislator-photos/412580-200px.jpeg", fav: false },
{us_state: "WA", vote: "Yes", party: "Democrat", name: "Rep. Derek Kilmer [D]", img: "https://www.govtrack.us/static/legislator-photos/412583-200px.jpeg", fav: false },
{us_state: "WA", vote: "Yes", party: "Democrat", name: "Rep. Denny Heck [D]", img: "https://www.govtrack.us/static/legislator-photos/412584-200px.jpeg", fav: false },
{us_state: "WI", vote: "Yes", party: "Democrat", name: "Rep. Mark Pocan [D]", img: "https://www.govtrack.us/static/legislator-photos/412585-200px.jpeg", fav: false },
{us_state: "IL", vote: "Yes", party: "Democrat", name: "Rep. Robin Kelly [D]", img: "https://www.govtrack.us/static/legislator-photos/412595-200px.jpeg", fav: false },
{us_state: "MA", vote: "Yes", party: "Democrat", name: "Rep. Katherine Clark [D]", img: "https://www.govtrack.us/static/legislator-photos/412600-200px.jpeg", fav: false },
{us_state: "NJ", vote: "Yes", party: "Democrat", name: "Rep. Donald Norcross [D]", img: "https://www.govtrack.us/static/legislator-photos/412606-200px.jpeg", fav: false },
{us_state: "NC", vote: "Yes", party: "Democrat", name: "Rep. Alma Adams [D]", img: "https://www.govtrack.us/static/legislator-photos/412607-200px.jpeg", fav: false },
{us_state: "AZ", vote: "Yes", party: "Democrat", name: "Rep. Ruben Gallego [D]", img: "https://www.govtrack.us/static/legislator-photos/412612-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Mark DeSaulnier [D]", img: "https://www.govtrack.us/static/legislator-photos/412613-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Pete Aguilar [D]", img: "https://www.govtrack.us/static/legislator-photos/412615-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Ted Lieu [D]", img: "https://www.govtrack.us/static/legislator-photos/412616-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Norma Torres [D]", img: "https://www.govtrack.us/static/legislator-photos/412617-200px.jpeg", fav: false },
{us_state: "MA", vote: "Abstained", party: "Democrat", name: "Rep. Seth Moulton [D]", img: "https://www.govtrack.us/static/legislator-photos/412632-200px.jpeg", fav: false },
{us_state: "MI", vote: "Abstained", party: "Democrat", name: "Rep. Debbie Dingell [D]", img: "https://www.govtrack.us/static/legislator-photos/412637-200px.jpeg", fav: false },
{us_state: "MI", vote: "Yes", party: "Democrat", name: "Rep. Brenda Lawrence [D]", img: "https://www.govtrack.us/static/legislator-photos/412638-200px.jpeg", fav: false },
{us_state: "NJ", vote: "Yes", party: "Democrat", name: "Rep. Bonnie Watson Coleman [D]", img: "https://www.govtrack.us/static/legislator-photos/412644-200px.jpeg", fav: false },
{us_state: "NY", vote: "Yes", party: "Democrat", name: "Rep. Kathleen Rice [D]", img: "https://www.govtrack.us/static/legislator-photos/412647-200px.jpeg", fav: false },
{us_state: "PA", vote: "Yes", party: "Democrat", name: "Rep. Brendan Boyle [D]", img: "https://www.govtrack.us/static/legislator-photos/412652-200px.jpeg", fav: false },
{us_state: "VA", vote: "Yes", party: "Democrat", name: "Rep. Donald Beyer [D]", img: "https://www.govtrack.us/static/legislator-photos/412657-200px.jpeg", fav: false },
{us_state: "PA", vote: "Yes", party: "Democrat", name: "Rep. Dwight Evans [D]", img: "https://www.govtrack.us/static/legislator-photos/412677-200px.jpeg", fav: false },
{us_state: "AZ", vote: "Yes", party: "Democrat", name: "Rep. Tom O’Halleran [D]", img: "https://www.govtrack.us/static/legislator-photos/412682-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Ro Khanna [D]", img: "https://www.govtrack.us/static/legislator-photos/412684-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Jimmy Panetta [D]", img: "https://www.govtrack.us/static/legislator-photos/412685-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Salud Carbajal [D]", img: "https://www.govtrack.us/static/legislator-photos/412686-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Nanette Barragán [D]", img: "https://www.govtrack.us/static/legislator-photos/412687-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Luis Correa [D]", img: "https://www.govtrack.us/static/legislator-photos/412688-200px.jpeg", fav: false },
{us_state: "DE", vote: "Yes", party: "Democrat", name: "Rep. Lisa Blunt Rochester [D]", img: "https://www.govtrack.us/static/legislator-photos/412689-200px.jpeg", fav: false },
{us_state: "FL", vote: "Yes", party: "Democrat", name: "Rep. Al Lawson [D]", img: "https://www.govtrack.us/static/legislator-photos/412693-200px.jpeg", fav: false },
{us_state: "FL", vote: "Yes", party: "Democrat", name: "Rep. Stephanie Murphy [D]", img: "https://www.govtrack.us/static/legislator-photos/412694-200px.jpeg", fav: false },
{us_state: "FL", vote: "Yes", party: "Democrat", name: "Rep. Darren Soto [D]", img: "https://www.govtrack.us/static/legislator-photos/412695-200px.jpeg", fav: false },
{us_state: "FL", vote: "Yes", party: "Democrat", name: "Rep. Val Demings [D]", img: "https://www.govtrack.us/static/legislator-photos/412696-200px.jpeg", fav: false },
{us_state: "FL", vote: "Yes", party: "Democrat", name: "Rep. Charlie Crist [D]", img: "https://www.govtrack.us/static/legislator-photos/412697-200px.jpeg", fav: false },
{us_state: "IL", vote: "Yes", party: "Democrat", name: "Rep. Raja Krishnamoorthi [D]", img: "https://www.govtrack.us/static/legislator-photos/412701-200px.jpeg", fav: false },
{us_state: "MD", vote: "Yes", party: "Democrat", name: "Rep. Anthony Brown [D]", img: "https://www.govtrack.us/static/legislator-photos/412707-200px.jpeg", fav: false },
{us_state: "MD", vote: "Yes", party: "Democrat", name: "Rep. Jamie Raskin [D]", img: "https://www.govtrack.us/static/legislator-photos/412708-200px.jpeg", fav: false },
{us_state: "NJ", vote: "Yes", party: "Democrat", name: "Rep. Josh Gottheimer [D]", img: "https://www.govtrack.us/static/legislator-photos/412714-200px.jpeg", fav: false },
{us_state: "NY", vote: "Yes", party: "Democrat", name: "Rep. Thomas Suozzi [D]", img: "https://www.govtrack.us/static/legislator-photos/412717-200px.jpeg", fav: false },
{us_state: "NY", vote: "Yes", party: "Democrat", name: "Rep. Adriano Espaillat [D]", img: "https://www.govtrack.us/static/legislator-photos/412718-200px.jpeg", fav: false },
{us_state: "TX", vote: "Yes", party: "Democrat", name: "Rep. Vicente Gonzalez [D]", img: "https://www.govtrack.us/static/legislator-photos/412725-200px.jpeg", fav: false },
{us_state: "VA", vote: "Yes", party: "Democrat", name: "Rep. Donald McEachin [D]", img: "https://www.govtrack.us/static/legislator-photos/412728-200px.jpeg", fav: false },
{us_state: "WA", vote: "Yes", party: "Democrat", name: "Rep. Pramila Jayapal [D]", img: "https://www.govtrack.us/static/legislator-photos/412730-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Jimmy Gomez [D]", img: "https://www.govtrack.us/static/legislator-photos/412739-200px.jpeg", fav: false },
{us_state: "PA", vote: "Yes", party: "Democrat", name: "Rep. Conor Lamb [D]", img: "https://www.govtrack.us/static/legislator-photos/412744-200px.jpeg", fav: false },
{us_state: "NY", vote: "Yes", party: "Democrat", name: "Rep. Joseph Morelle [D]", img: "https://www.govtrack.us/static/legislator-photos/412749-200px.jpeg", fav: false },
{us_state: "PA", vote: "Yes", party: "Democrat", name: "Rep. Mary Scanlon [D]", img: "https://www.govtrack.us/static/legislator-photos/412750-200px.jpeg", fav: false },
{us_state: "PA", vote: "Yes", party: "Democrat", name: "Rep. Susan Wild [D]", img: "https://www.govtrack.us/static/legislator-photos/412751-200px.jpeg", fav: false },
{us_state: "AZ", vote: "Yes", party: "Democrat", name: "Rep. Greg Stanton [D]", img: "https://www.govtrack.us/static/legislator-photos/412753-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Josh Harder [D]", img: "https://www.govtrack.us/static/legislator-photos/412754-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. TJ Cox [D]", img: "https://www.govtrack.us/static/legislator-photos/412755-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Katie Hill [D]", img: "https://www.govtrack.us/static/legislator-photos/412756-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Gilbert Cisneros [D]", img: "https://www.govtrack.us/static/legislator-photos/412757-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Katie Porter [D]", img: "https://www.govtrack.us/static/legislator-photos/412758-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Harley Rouda [D]", img: "https://www.govtrack.us/static/legislator-photos/412759-200px.jpeg", fav: false },
{us_state: "CA", vote: "Yes", party: "Democrat", name: "Rep. Mike Levin [D]", img: "https://www.govtrack.us/static/legislator-photos/412760-200px.jpeg", fav: false },
{us_state: "CO", vote: "Yes", party: "Democrat", name: "Rep. Joe Neguse [D]", img: "https://www.govtrack.us/static/legislator-photos/412761-200px.jpeg", fav: false },
{us_state: "CO", vote: "Yes", party: "Democrat", name: "Rep. Jason Crow [D]", img: "https://www.govtrack.us/static/legislator-photos/412762-200px.jpeg", fav: false },
{us_state: "CT", vote: "Yes", party: "Democrat", name: "Rep. Jahana Hayes [D]", img: "https://www.govtrack.us/static/legislator-photos/412763-200px.jpeg", fav: false },
{us_state: "FL", vote: "Yes", party: "Democrat", name: "Rep. Debbie Mucarsel-Powell [D]", img: "https://www.govtrack.us/static/legislator-photos/412767-200px.jpeg", fav: false },
{us_state: "FL", vote: "Yes", party: "Democrat", name: "Rep. Donna Shalala [D]", img: "https://www.govtrack.us/static/legislator-photos/412768-200px.jpeg", fav: false },
{us_state: "GA", vote: "Yes", party: "Democrat", name: "Rep. Lucy McBath [D]", img: "https://www.govtrack.us/static/legislator-photos/412769-200px.jpeg", fav: false },
{us_state: "IA", vote: "Yes", party: "Democrat", name: "Rep. Abby Finkenauer [D]", img: "https://www.govtrack.us/static/legislator-photos/412771-200px.jpeg", fav: false },
{us_state: "IA", vote: "Yes", party: "Democrat", name: "Rep. Cynthia Axne [D]", img: "https://www.govtrack.us/static/legislator-photos/412772-200px.jpeg", fav: false },
{us_state: "IL", vote: "Yes", party: "Democrat", name: "Rep. Jesús García [D]", img: "https://www.govtrack.us/static/legislator-photos/412774-200px.jpeg", fav: false },
{us_state: "IL", vote: "Yes", party: "Democrat", name: "Rep. Sean Casten [D]", img: "https://www.govtrack.us/static/legislator-photos/412775-200px.jpeg", fav: false },
{us_state: "IL", vote: "Yes", party: "Democrat", name: "Rep. Lauren Underwood [D]", img: "https://www.govtrack.us/static/legislator-photos/412776-200px.jpeg", fav: false },
{us_state: "KS", vote: "Yes", party: "Democrat", name: "Rep. Sharice Davids [D]", img: "https://www.govtrack.us/static/legislator-photos/412780-200px.jpeg", fav: false },
{us_state: "MA", vote: "Yes", party: "Democrat", name: "Rep. Lori Trahan [D]", img: "https://www.govtrack.us/static/legislator-photos/412781-200px.jpeg", fav: false },
{us_state: "MA", vote: "Yes", party: "Democrat", name: "Rep. Ayanna Pressley [D]", img: "https://www.govtrack.us/static/legislator-photos/412782-200px.jpeg", fav: false },
{us_state: "MD", vote: "Yes", party: "Democrat", name: "Rep. David Trone [D]", img: "https://www.govtrack.us/static/legislator-photos/412783-200px.jpeg", fav: false },
{us_state: "MI", vote: "Yes", party: "Democrat", name: "Rep. Elissa Slotkin [D]", img: "https://www.govtrack.us/static/legislator-photos/412784-200px.jpeg", fav: false },
{us_state: "MI", vote: "Yes", party: "Democrat", name: "Rep. Andy Levin [D]", img: "https://www.govtrack.us/static/legislator-photos/412785-200px.jpeg", fav: false },
{us_state: "MI", vote: "Yes", party: "Democrat", name: "Rep. Haley Stevens [D]", img: "https://www.govtrack.us/static/legislator-photos/412786-200px.jpeg", fav: false },
{us_state: "MI", vote: "Yes", party: "Democrat", name: "Rep. Rashida Tlaib [D]", img: "https://www.govtrack.us/static/legislator-photos/412787-200px.jpeg", fav: false },
{us_state: "MN", vote: "Yes", party: "Democrat", name: "Rep. Angie Craig [D]", img: "https://www.govtrack.us/static/legislator-photos/412789-200px.jpeg", fav: false },
{us_state: "MN", vote: "Yes", party: "Democrat", name: "Rep. Dean Phillips [D]", img: "https://www.govtrack.us/static/legislator-photos/412790-200px.jpeg", fav: false },
{us_state: "MN", vote: "Yes", party: "Democrat", name: "Rep. Ilhan Omar [D]", img: "https://www.govtrack.us/static/legislator-photos/412791-200px.jpeg", fav: false },
{us_state: "NH", vote: "Yes", party: "Democrat", name: "Rep. Chris Pappas [D]", img: "https://www.govtrack.us/static/legislator-photos/412795-200px.jpeg", fav: false },
{us_state: "NJ", vote: "Yes", party: "Democrat", name: "Rep. Jefferson Van Drew [D]", img: "https://www.govtrack.us/static/legislator-photos/412796-200px.jpeg", fav: false },
{us_state: "NJ", vote: "Yes", party: "Democrat", name: "Rep. Andy Kim [D]", img: "https://www.govtrack.us/static/legislator-photos/412797-200px.jpeg", fav: false },
{us_state: "NJ", vote: "Yes", party: "Democrat", name: "Rep. Tom Malinowski [D]", img: "https://www.govtrack.us/static/legislator-photos/412798-200px.jpeg", fav: false },
{us_state: "NJ", vote: "Yes", party: "Democrat", name: "Rep. Mikie Sherrill [D]", img: "https://www.govtrack.us/static/legislator-photos/412799-200px.jpeg", fav: false },
{us_state: "NM", vote: "Yes", party: "Democrat", name: "Rep. Debra Haaland [D]", img: "https://www.govtrack.us/static/legislator-photos/412800-200px.jpeg", fav: false },
{us_state: "NM", vote: "Yes", party: "Democrat", name: "Rep. Xochitl Torres Small [D]", img: "https://www.govtrack.us/static/legislator-photos/412801-200px.jpeg", fav: false },
{us_state: "NV", vote: "Yes", party: "Democrat", name: "Rep. Susie Lee [D]", img: "https://www.govtrack.us/static/legislator-photos/412802-200px.jpeg", fav: false },
{us_state: "NY", vote: "Abstained", party: "Democrat", name: "Rep. Max Rose [D]", img: "https://www.govtrack.us/static/legislator-photos/412803-200px.jpeg", fav: false },
{us_state: "NY", vote: "Yes", party: "Democrat", name: "Rep. Alexandria Ocasio-Cortez [D]", img: "https://www.govtrack.us/static/legislator-photos/412804-200px.jpeg", fav: false },
{us_state: "NY", vote: "Yes", party: "Democrat", name: "Rep. Antonio Delgado [D]", img: "https://www.govtrack.us/static/legislator-photos/412805-200px.jpeg", fav: false },
{us_state: "NY", vote: "Yes", party: "Democrat", name: "Rep. Anthony Brindisi [D]", img: "https://www.govtrack.us/static/legislator-photos/412806-200px.jpeg", fav: false },
{us_state: "OK", vote: "Yes", party: "Democrat", name: "Rep. Kendra Horn [D]", img: "https://www.govtrack.us/static/legislator-photos/412808-200px.jpeg", fav: false },
{us_state: "PA", vote: "Yes", party: "Democrat", name: "Rep. Madeleine Dean [D]", img: "https://www.govtrack.us/static/legislator-photos/412809-200px.jpeg", fav: false },
{us_state: "PA", vote: "Yes", party: "Democrat", name: "Rep. Chrissy Houlahan [D]", img: "https://www.govtrack.us/static/legislator-photos/412810-200px.jpeg", fav: false },
{us_state: "SC", vote: "Yes", party: "Democrat", name: "Rep. Joe Cunningham [D]", img: "https://www.govtrack.us/static/legislator-photos/412814-200px.jpeg", fav: false },
{us_state: "TX", vote: "Yes", party: "Democrat", name: "Rep. Lizzie Fletcher [D]", img: "https://www.govtrack.us/static/legislator-photos/412824-200px.jpeg", fav: false },
{us_state: "TX", vote: "Yes", party: "Democrat", name: "Rep. Veronica Escobar [D]", img: "https://www.govtrack.us/static/legislator-photos/412825-200px.jpeg", fav: false },
{us_state: "TX", vote: "Yes", party: "Democrat", name: "Rep. Sylvia Garcia [D]", img: "https://www.govtrack.us/static/legislator-photos/412827-200px.jpeg", fav: false },
{us_state: "TX", vote: "Yes", party: "Democrat", name: "Rep. Colin Allred [D]", img: "https://www.govtrack.us/static/legislator-photos/412828-200px.jpeg", fav: false },
{us_state: "UT", vote: "Yes", party: "Democrat", name: "Rep. Ben McAdams [D]", img: "https://www.govtrack.us/static/legislator-photos/412829-200px.jpeg", fav: false },
{us_state: "VA", vote: "Yes", party: "Democrat", name: "Rep. Elaine Luria [D]", img: "https://www.govtrack.us/static/legislator-photos/412830-200px.jpeg", fav: false },
{us_state: "VA", vote: "Yes", party: "Democrat", name: "Rep. Abigail Spanberger [D]", img: "https://www.govtrack.us/static/legislator-photos/412833-200px.jpeg", fav: false },
{us_state: "VA", vote: "Yes", party: "Democrat", name: "Rep. Jennifer Wexton [D]", img: "https://www.govtrack.us/static/legislator-photos/412834-200px.jpeg", fav: false },
{us_state: "WA", vote: "Yes", party: "Democrat", name: "Rep. Kim Schrier [D]", img: "https://www.govtrack.us/static/legislator-photos/412835-200px.jpeg", fav: false },
{us_state: "ME", vote: "Yes", party: "Democrat", name: "Rep. Jared Golden [D]", img: "https://www.govtrack.us/static/legislator-photos/412842-200px.jpeg", fav: false },
{us_state: "AL", vote: "No", party: "Republican", name: "Rep. Robert Aderholt [R]", img: "https://www.govtrack.us/static/legislator-photos/400004-200px.jpeg", fav: false },
{us_state: "UT", vote: "No", party: "Republican", name: "Rep. Rob Bishop [R]", img: "https://www.govtrack.us/static/legislator-photos/400029-200px.jpeg", fav: false },
{us_state: "TX", vote: "Abstained", party: "Republican", name: "Rep. Kevin Brady [R]", img: "https://www.govtrack.us/static/legislator-photos/400046-200px.jpeg", fav: false },
{us_state: "TX", vote: "No", party: "Republican", name: "Rep. Michael Burgess [R]", img: "https://www.govtrack.us/static/legislator-photos/400052-200px.jpeg", fav: false },
{us_state: "CA", vote: "No", party: "Republican", name: "Rep. Ken Calvert [R]", img: "https://www.govtrack.us/static/legislator-photos/400057-200px.jpeg", fav: false },
{us_state: "TX", vote: "No", party: "Republican", name: "Rep. John Carter [R]", img: "https://www.govtrack.us/static/legislator-photos/400068-200px.jpeg", fav: false },
{us_state: "OH", vote: "No", party: "Republican", name: "Rep. Steve Chabot [R]", img: "https://www.govtrack.us/static/legislator-photos/400071-200px.jpeg", fav: false },
{us_state: "OK", vote: "No", party: "Republican", name: "Rep. Tom Cole [R]", img: "https://www.govtrack.us/static/legislator-photos/400077-200px.jpeg", fav: false },
{us_state: "FL", vote: "Yes", party: "Republican", name: "Rep. Mario Diaz-Balart [R]", img: "https://www.govtrack.us/static/legislator-photos/400108-200px.jpeg", fav: false },
{us_state: "TX", vote: "No", party: "Republican", name: "Rep. Kay Granger [R]", img: "https://www.govtrack.us/static/legislator-photos/400157-200px.jpeg", fav: false },
{us_state: "MO", vote: "No", party: "Republican", name: "Rep. Sam Graves [R]", img: "https://www.govtrack.us/static/legislator-photos/400158-200px.jpeg", fav: false },
{us_state: "NY", vote: "No", party: "Republican", name: "Rep. Peter “Pete” King [R]", img: "https://www.govtrack.us/static/legislator-photos/400219-200px.jpeg", fav: false },
{us_state: "IA", vote: "No", party: "Republican", name: "Rep. Steve King [R]", img: "https://www.govtrack.us/static/legislator-photos/400220-200px.jpeg", fav: false },
{us_state: "OK", vote: "No", party: "Republican", name: "Rep. Frank Lucas [R]", img: "https://www.govtrack.us/static/legislator-photos/400247-200px.jpeg", fav: false },
{us_state: "CA", vote: "No", party: "Republican", name: "Rep. Devin Nunes [R]", img: "https://www.govtrack.us/static/legislator-photos/400297-200px.jpeg", fav: false },
{us_state: "KY", vote: "No", party: "Republican", name: "Rep. Harold “Hal” Rogers [R]", img: "https://www.govtrack.us/static/legislator-photos/400340-200px.jpeg", fav: false },
{us_state: "AL", vote: "No", party: "Republican", name: "Rep. Mike Rogers [R]", img: "https://www.govtrack.us/static/legislator-photos/400341-200px.jpeg", fav: false },
{us_state: "WI", vote: "No", party: "Republican", name: "Rep. James Sensenbrenner Jr. [R]", img: "https://www.govtrack.us/static/legislator-photos/400365-200px.jpeg", fav: false },
{us_state: "IL", vote: "No", party: "Republican", name: "Rep. John Shimkus [R]", img: "https://www.govtrack.us/static/legislator-photos/400373-200px.jpeg", fav: false },
{us_state: "ID", vote: "No", party: "Republican", name: "Rep. Michael “Mike” Simpson [R]", img: "https://www.govtrack.us/static/legislator-photos/400376-200px.jpeg", fav: false },
{us_state: "NJ", vote: "No", party: "Republican", name: "Rep. Christopher “Chris” Smith [R]", img: "https://www.govtrack.us/static/legislator-photos/400380-200px.jpeg", fav: false },
{us_state: "TX", vote: "No", party: "Republican", name: "Rep. Mac Thornberry [R]", img: "https://www.govtrack.us/static/legislator-photos/400404-200px.jpeg", fav: false },
{us_state: "OH", vote: "Abstained", party: "Republican", name: "Rep. Michael Turner [R]", img: "https://www.govtrack.us/static/legislator-photos/400411-200px.jpeg", fav: false },
{us_state: "MI", vote: "No", party: "Republican", name: "Rep. Fred Upton [R]", img: "https://www.govtrack.us/static/legislator-photos/400414-200px.jpeg", fav: false },
{us_state: "OR", vote: "Yes", party: "Republican", name: "Rep. Greg Walden [R]", img: "https://www.govtrack.us/static/legislator-photos/400419-200px.jpeg", fav: false },
{us_state: "SC", vote: "Abstained", party: "Republican", name: "Rep. Joe Wilson [R]", img: "https://www.govtrack.us/static/legislator-photos/400433-200px.jpeg", fav: false },
{us_state: "AK", vote: "Abstained", party: "Republican", name: "Rep. Don Young [R]", img: "https://www.govtrack.us/static/legislator-photos/400440-200px.jpeg", fav: false },
{us_state: "NE", vote: "No", party: "Republican", name: "Rep. Jeff Fortenberry [R]", img: "https://www.govtrack.us/static/legislator-photos/400640-200px.jpeg", fav: false },
{us_state: "NC", vote: "No", party: "Republican", name: "Rep. Virginia Foxx [R]", img: "https://www.govtrack.us/static/legislator-photos/400643-200px.jpeg", fav: false },
{us_state: "NC", vote: "No", party: "Republican", name: "Rep. Patrick McHenry [R]", img: "https://www.govtrack.us/static/legislator-photos/400644-200px.jpeg", fav: false },
{us_state: "TX", vote: "No", party: "Republican", name: "Rep. Louie Gohmert Jr. [R]", img: "https://www.govtrack.us/static/legislator-photos/400651-200px.jpeg", fav: false },
{us_state: "TX", vote: "No", party: "Republican", name: "Rep. Michael McCaul [R]", img: "https://www.govtrack.us/static/legislator-photos/400654-200px.jpeg", fav: false },
{us_state: "TX", vote: "No", party: "Republican", name: "Rep. Michael Conaway [R]", img: "https://www.govtrack.us/static/legislator-photos/400655-200px.jpeg", fav: false },
{us_state: "TX", vote: "No", party: "Republican", name: "Rep. Kenny Marchant [R]", img: "https://www.govtrack.us/static/legislator-photos/400656-200px.jpeg", fav: false },
{us_state: "WA", vote: "No", party: "Republican", name: "Rep. Cathy McMorris Rodgers [R]", img: "https://www.govtrack.us/static/legislator-photos/400659-200px.jpeg", fav: false },
{us_state: "CA", vote: "No", party: "Republican", name: "Rep. Kevin McCarthy [R]", img: "https://www.govtrack.us/static/legislator-photos/412190-200px.jpeg", fav: false },
{us_state: "CO", vote: "No", party: "Republican", name: "Rep. Doug Lamborn [R]", img: "https://www.govtrack.us/static/legislator-photos/412191-200px.jpeg", fav: false },
{us_state: "FL", vote: "No", party: "Republican", name: "Rep. Vern Buchanan [R]", img: "https://www.govtrack.us/static/legislator-photos/412196-200px.jpeg", fav: false },
{us_state: "MI", vote: "No", party: "Republican", name: "Rep. Tim Walberg [R]", img: "https://www.govtrack.us/static/legislator-photos/412213-200px.jpeg", fav: false },
{us_state: "NE", vote: "No", party: "Republican", name: "Rep. Adrian Smith [R]", img: "https://www.govtrack.us/static/legislator-photos/412217-200px.jpeg", fav: false },
{us_state: "OH", vote: "No", party: "Republican", name: "Rep. Jim Jordan [R]", img: "https://www.govtrack.us/static/legislator-photos/412226-200px.jpeg", fav: false },
{us_state: "FL", vote: "No", party: "Republican", name: "Rep. Gus Bilirakis [R]", img: "https://www.govtrack.us/static/legislator-photos/412250-200px.jpeg", fav: false },
{us_state: "VA", vote: "No", party: "Republican", name: "Rep. Robert Wittman [R]", img: "https://www.govtrack.us/static/legislator-photos/412255-200px.jpeg", fav: false },
{us_state: "OH", vote: "No", party: "Republican", name: "Rep. Robert Latta [R]", img: "https://www.govtrack.us/static/legislator-photos/412256-200px.jpeg", fav: false },
{us_state: "LA", vote: "No", party: "Republican", name: "Rep. Steve Scalise [R]", img: "https://www.govtrack.us/static/legislator-photos/412261-200px.jpeg", fav: false },
{us_state: "KY", vote: "No", party: "Republican", name: "Rep. Brett Guthrie [R]", img: "https://www.govtrack.us/static/legislator-photos/412278-200px.jpeg", fav: false },
{us_state: "CA", vote: "No", party: "Republican", name: "Rep. Duncan Hunter [R]", img: "https://www.govtrack.us/static/legislator-photos/412283-200px.jpeg", fav: false },
{us_state: "MO", vote: "No", party: "Republican", name: "Rep. Blaine Luetkemeyer [R]", img: "https://www.govtrack.us/static/legislator-photos/412292-200px.jpeg", fav: false },
{us_state: "CA", vote: "No", party: "Republican", name: "Rep. Tom McClintock [R]", img: "https://www.govtrack.us/static/legislator-photos/412295-200px.jpeg", fav: false },
{us_state: "TX", vote: "No", party: "Republican", name: "Rep. Pete Olson [R]", img: "https://www.govtrack.us/static/legislator-photos/412302-200px.jpeg", fav: false },
{us_state: "FL", vote: "No", party: "Republican", name: "Rep. Bill Posey [R]", img: "https://www.govtrack.us/static/legislator-photos/412309-200px.jpeg", fav: false },
{us_state: "TN", vote: "No", party: "Republican", name: "Rep. David “Phil” Roe [R]", img: "https://www.govtrack.us/static/legislator-photos/412310-200px.jpeg", fav: false },
{us_state: "PA", vote: "No", party: "Republican", name: "Rep. Glenn Thompson [R]", img: "https://www.govtrack.us/static/legislator-photos/412317-200px.jpeg", fav: false },
{us_state: "GA", vote: "No", party: "Republican", name: "Rep. Tom Graves [R]", img: "https://www.govtrack.us/static/legislator-photos/412388-200px.jpeg", fav: false },
{us_state: "NY", vote: "Yes", party: "Republican", name: "Rep. Tom Reed II [R]", img: "https://www.govtrack.us/static/legislator-photos/412393-200px.jpeg", fav: false },
{us_state: "AL", vote: "No", party: "Republican", name: "Rep. Martha Roby [R]", img: "https://www.govtrack.us/static/legislator-photos/412394-200px.jpeg", fav: false },
{us_state: "AL", vote: "No", party: "Republican", name: "Rep. Mo Brooks [R]", img: "https://www.govtrack.us/static/legislator-photos/412395-200px.jpeg", fav: false },
{us_state: "AZ", vote: "No", party: "Republican", name: "Rep. Paul Gosar [R]", img: "https://www.govtrack.us/static/legislator-photos/412397-200px.jpeg", fav: false },
{us_state: "AZ", vote: "No", party: "Republican", name: "Rep. David Schweikert [R]", img: "https://www.govtrack.us/static/legislator-photos/412399-200px.jpeg", fav: false },
{us_state: "AR", vote: "No", party: "Republican", name: "Rep. Eric “Rick” Crawford [R]", img: "https://www.govtrack.us/static/legislator-photos/412400-200px.jpeg", fav: false },
{us_state: "AR", vote: "No", party: "Republican", name: "Rep. Steve Womack [R]", img: "https://www.govtrack.us/static/legislator-photos/412402-200px.jpeg", fav: false },
{us_state: "CO", vote: "No", party: "Republican", name: "Rep. Scott Tipton [R]", img: "https://www.govtrack.us/static/legislator-photos/412405-200px.jpeg", fav: false },
{us_state: "FL", vote: "No", party: "Republican", name: "Rep. Daniel Webster [R]", img: "https://www.govtrack.us/static/legislator-photos/412410-200px.jpeg", fav: false },
{us_state: "GA", vote: "No", party: "Republican", name: "Rep. Rob Woodall [R]", img: "https://www.govtrack.us/static/legislator-photos/412416-200px.jpeg", fav: false },
{us_state: "GA", vote: "No", party: "Republican", name: "Rep. Austin Scott [R]", img: "https://www.govtrack.us/static/legislator-photos/412417-200px.jpeg", fav: false },
{us_state: "IL", vote: "No", party: "Republican", name: "Rep. Adam Kinzinger [R]", img: "https://www.govtrack.us/static/legislator-photos/412421-200px.jpeg", fav: false },
{us_state: "IN", vote: "Abstained", party: "Republican", name: "Rep. Larry Bucshon [R]", img: "https://www.govtrack.us/static/legislator-photos/412427-200px.jpeg", fav: false },
{us_state: "MD", vote: "No", party: "Republican", name: "Rep. Andy Harris [R]", img: "https://www.govtrack.us/static/legislator-photos/412434-200px.jpeg", fav: false },
{us_state: "MI", vote: "No", party: "Republican", name: "Rep. Bill Huizenga [R]", img: "https://www.govtrack.us/static/legislator-photos/412437-200px.jpeg", fav: false },
{us_state: "MI", vote: "No", party: "Republican", name: "Rep. Justin Amash [I]", img: "https://www.govtrack.us/static/legislator-photos/412438-200px.jpeg", fav: false },
{us_state: "MS", vote: "No", party: "Republican", name: "Rep. Steven Palazzo [R]", img: "https://www.govtrack.us/static/legislator-photos/412443-200px.jpeg", fav: false },
{us_state: "MO", vote: "No", party: "Republican", name: "Rep. Vicky Hartzler [R]", img: "https://www.govtrack.us/static/legislator-photos/412444-200px.jpeg", fav: false },
{us_state: "MO", vote: "No", party: "Republican", name: "Rep. Billy Long [R]", img: "https://www.govtrack.us/static/legislator-photos/412445-200px.jpeg", fav: false },
{us_state: "OH", vote: "Abstained", party: "Republican", name: "Rep. Bill Johnson [R]", img: "https://www.govtrack.us/static/legislator-photos/412460-200px.jpeg", fav: false },
{us_state: "OH", vote: "No", party: "Republican", name: "Rep. Steve Stivers [R]", img: "https://www.govtrack.us/static/legislator-photos/412461-200px.jpeg", fav: false },
{us_state: "OH", vote: "No", party: "Republican", name: "Rep. Bob Gibbs [R]", img: "https://www.govtrack.us/static/legislator-photos/412463-200px.jpeg", fav: false },
{us_state: "PA", vote: "No", party: "Republican", name: "Rep. Mike Kelly [R]", img: "https://www.govtrack.us/static/legislator-photos/412465-200px.jpeg", fav: false },
{us_state: "SC", vote: "No", party: "Republican", name: "Rep. Jeff Duncan [R]", img: "https://www.govtrack.us/static/legislator-photos/412472-200px.jpeg", fav: false },
{us_state: "TN", vote: "No", party: "Republican", name: "Rep. Charles “Chuck” Fleischmann [R]", img: "https://www.govtrack.us/static/legislator-photos/412476-200px.jpeg", fav: false },
{us_state: "TN", vote: "No", party: "Republican", name: "Rep. Scott DesJarlais [R]", img: "https://www.govtrack.us/static/legislator-photos/412477-200px.jpeg", fav: false },
{us_state: "TX", vote: "No", party: "Republican", name: "Rep. Bill Flores [R]", img: "https://www.govtrack.us/static/legislator-photos/412480-200px.jpeg", fav: false },
{us_state: "VA", vote: "No", party: "Republican", name: "Rep. Morgan Griffith [R]", img: "https://www.govtrack.us/static/legislator-photos/412485-200px.jpeg", fav: false },
{us_state: "WA", vote: "No", party: "Republican", name: "Rep. Jaime Herrera Beutler [R]", img: "https://www.govtrack.us/static/legislator-photos/412486-200px.jpeg", fav: false },
{us_state: "WV", vote: "No", party: "Republican", name: "Rep. David McKinley [R]", img: "https://www.govtrack.us/static/legislator-photos/412487-200px.jpeg", fav: false },
{us_state: "WI", vote: "Abstained", party: "Republican", name: "Rep. Sean Duffy [R]", img: "https://www.govtrack.us/static/legislator-photos/412488-200px.jpeg", fav: false },
{us_state: "NV", vote: "No", party: "Republican", name: "Rep. Mark Amodei [R]", img: "https://www.govtrack.us/static/legislator-photos/412500-200px.jpeg", fav: false },
{us_state: "KY", vote: "No", party: "Republican", name: "Rep. Thomas Massie [R]", img: "https://www.govtrack.us/static/legislator-photos/412503-200px.jpeg", fav: false },
{us_state: "CA", vote: "No", party: "Republican", name: "Rep. Doug LaMalfa [R]", img: "https://www.govtrack.us/static/legislator-photos/412510-200px.jpeg", fav: false },
{us_state: "CA", vote: "No", party: "Republican", name: "Rep. Paul Cook [R]", img: "https://www.govtrack.us/static/legislator-photos/412513-200px.jpeg", fav: false },
{us_state: "FL", vote: "No", party: "Republican", name: "Rep. Ted Yoho [R]", img: "https://www.govtrack.us/static/legislator-photos/412525-200px.jpeg", fav: false },
{us_state: "GA", vote: "No", party: "Republican", name: "Rep. Doug Collins [R]", img: "https://www.govtrack.us/static/legislator-photos/412531-200px.jpeg", fav: false },
{us_state: "IL", vote: "No", party: "Republican", name: "Rep. Rodney Davis [R]", img: "https://www.govtrack.us/static/legislator-photos/412536-200px.jpeg", fav: false },
{us_state: "IN", vote: "No", party: "Republican", name: "Rep. Jackie Walorski [R]", img: "https://www.govtrack.us/static/legislator-photos/412538-200px.jpeg", fav: false },
{us_state: "IN", vote: "Yes", party: "Republican", name: "Rep. Susan Brooks [R]", img: "https://www.govtrack.us/static/legislator-photos/412539-200px.jpeg", fav: false },
{us_state: "KY", vote: "No", party: "Republican", name: "Rep. Garland “Andy” Barr [R]", img: "https://www.govtrack.us/static/legislator-photos/412541-200px.jpeg", fav: false },
{us_state: "MO", vote: "No", party: "Republican", name: "Rep. Ann Wagner [R]", img: "https://www.govtrack.us/static/legislator-photos/412548-200px.jpeg", fav: false },
{us_state: "NC", vote: "No", party: "Republican", name: "Rep. Richard Hudson [R]", img: "https://www.govtrack.us/static/legislator-photos/412550-200px.jpeg", fav: false },
{us_state: "NC", vote: "No", party: "Republican", name: "Rep. Mark Meadows [R]", img: "https://www.govtrack.us/static/legislator-photos/412552-200px.jpeg", fav: false },
{us_state: "NC", vote: "No", party: "Republican", name: "Rep. George Holding [R]", img: "https://www.govtrack.us/static/legislator-photos/412553-200px.jpeg", fav: false },
{us_state: "NY", vote: "No", party: "Republican", name: "Rep. Chris Collins [R]", img: "https://www.govtrack.us/static/legislator-photos/412563-200px.jpeg", fav: false },
{us_state: "OH", vote: "No", party: "Republican", name: "Rep. Brad Wenstrup [R]", img: "https://www.govtrack.us/static/legislator-photos/412564-200px.jpeg", fav: false },
{us_state: "OH", vote: "No", party: "Republican", name: "Rep. David Joyce [R]", img: "https://www.govtrack.us/static/legislator-photos/412566-200px.jpeg", fav: false },
{us_state: "OK", vote: "No", party: "Republican", name: "Rep. Markwayne Mullin [R]", img: "https://www.govtrack.us/static/legislator-photos/412568-200px.jpeg", fav: false },
{us_state: "PA", vote: "No", party: "Republican", name: "Rep. Scott Perry [R]", img: "https://www.govtrack.us/static/legislator-photos/412569-200px.jpeg", fav: false },
{us_state: "SC", vote: "No", party: "Republican", name: "Rep. Tom Rice [R]", img: "https://www.govtrack.us/static/legislator-photos/412572-200px.jpeg", fav: false },
{us_state: "TX", vote: "Abstained", party: "Republican", name: "Rep. Randy Weber [R]", img: "https://www.govtrack.us/static/legislator-photos/412574-200px.jpeg", fav: false },
{us_state: "TX", vote: "No", party: "Republican", name: "Rep. Roger Williams [R]", img: "https://www.govtrack.us/static/legislator-photos/412578-200px.jpeg", fav: false },
{us_state: "UT", vote: "No", party: "Republican", name: "Rep. Chris Stewart [R]", img: "https://www.govtrack.us/static/legislator-photos/412581-200px.jpeg", fav: false },
{us_state: "MO", vote: "No", party: "Republican", name: "Rep. Jason Smith [R]", img: "https://www.govtrack.us/static/legislator-photos/412596-200px.jpeg", fav: false },
{us_state: "AL", vote: "No", party: "Republican", name: "Rep. Bradley Byrne [R]", img: "https://www.govtrack.us/static/legislator-photos/412601-200px.jpeg", fav: false },
{us_state: "AL", vote: "No", party: "Republican", name: "Rep. Gary Palmer [R]", img: "https://www.govtrack.us/static/legislator-photos/412608-200px.jpeg", fav: false },
{us_state: "AR", vote: "No", party: "Republican", name: "Rep. French Hill [R]", img: "https://www.govtrack.us/static/legislator-photos/412609-200px.jpeg", fav: false },
{us_state: "AR", vote: "Abstained", party: "Republican", name: "Rep. Bruce Westerman [R]", img: "https://www.govtrack.us/static/legislator-photos/412610-200px.jpeg", fav: false },
{us_state: "CO", vote: "No", party: "Republican", name: "Rep. Ken Buck [R]", img: "https://www.govtrack.us/static/legislator-photos/412619-200px.jpeg", fav: false },
{us_state: "GA", vote: "No", party: "Republican", name: "Rep. Buddy Carter [R]", img: "https://www.govtrack.us/static/legislator-photos/412622-200px.jpeg", fav: false },
{us_state: "GA", vote: "No", party: "Republican", name: "Rep. Jody Hice [R]", img: "https://www.govtrack.us/static/legislator-photos/412623-200px.jpeg", fav: false },
{us_state: "GA", vote: "No", party: "Republican", name: "Rep. Barry Loudermilk [R]", img: "https://www.govtrack.us/static/legislator-photos/412624-200px.jpeg", fav: false },
{us_state: "GA", vote: "No", party: "Republican", name: "Rep. Rick Allen [R]", img: "https://www.govtrack.us/static/legislator-photos/412625-200px.jpeg", fav: false },
{us_state: "IL", vote: "No", party: "Republican", name: "Rep. Mike Bost [R]", img: "https://www.govtrack.us/static/legislator-photos/412629-200px.jpeg", fav: false },
{us_state: "LA", vote: "No", party: "Republican", name: "Rep. Ralph Abraham [R]", img: "https://www.govtrack.us/static/legislator-photos/412630-200px.jpeg", fav: false },
{us_state: "LA", vote: "No", party: "Republican", name: "Rep. Garret Graves [R]", img: "https://www.govtrack.us/static/legislator-photos/412631-200px.jpeg", fav: false },
{us_state: "MI", vote: "No", party: "Republican", name: "Rep. John Moolenaar [R]", img: "https://www.govtrack.us/static/legislator-photos/412634-200px.jpeg", fav: false },
{us_state: "MN", vote: "No", party: "Republican", name: "Rep. Tom Emmer [R]", img: "https://www.govtrack.us/static/legislator-photos/412639-200px.jpeg", fav: false },
{us_state: "NC", vote: "No", party: "Republican", name: "Rep. David Rouzer [R]", img: "https://www.govtrack.us/static/legislator-photos/412641-200px.jpeg", fav: false },
{us_state: "NY", vote: "No", party: "Republican", name: "Rep. Lee Zeldin [R]", img: "https://www.govtrack.us/static/legislator-photos/412646-200px.jpeg", fav: false },
{us_state: "NY", vote: "Yes", party: "Republican", name: "Rep. Elise Stefanik [R]", img: "https://www.govtrack.us/static/legislator-photos/412648-200px.jpeg", fav: false },
{us_state: "NY", vote: "Yes", party: "Republican", name: "Rep. John Katko [R]", img: "https://www.govtrack.us/static/legislator-photos/412649-200px.jpeg", fav: false },
{us_state: "TX", vote: "Abstained", party: "Republican", name: "Rep. John Ratcliffe [R]", img: "https://www.govtrack.us/static/legislator-photos/412653-200px.jpeg", fav: false },
{us_state: "TX", vote: "Yes", party: "Republican", name: "Rep. Will Hurd [R]", img: "https://www.govtrack.us/static/legislator-photos/412654-200px.jpeg", fav: false },
{us_state: "TX", vote: "No", party: "Republican", name: "Rep. Brian Babin [R]", img: "https://www.govtrack.us/static/legislator-photos/412655-200px.jpeg", fav: false },
{us_state: "WA", vote: "No", party: "Republican", name: "Rep. Dan Newhouse [R]", img: "https://www.govtrack.us/static/legislator-photos/412660-200px.jpeg", fav: false },
{us_state: "WI", vote: "No", party: "Republican", name: "Rep. Glenn Grothman [R]", img: "https://www.govtrack.us/static/legislator-photos/412661-200px.jpeg", fav: false },
{us_state: "WV", vote: "No", party: "Republican", name: "Rep. Alex Mooney [R]", img: "https://www.govtrack.us/static/legislator-photos/412662-200px.jpeg", fav: false },
{us_state: "NC", vote: "Abstained", party: "Republican", name: "Rep. Mark Walker [R]", img: "https://www.govtrack.us/static/legislator-photos/412670-200px.jpeg", fav: false },
{us_state: "MS", vote: "No", party: "Republican", name: "Rep. Trent Kelly [R]", img: "https://www.govtrack.us/static/legislator-photos/412673-200px.jpeg", fav: false },
{us_state: "IL", vote: "Abstained", party: "Republican", name: "Rep. Darin LaHood [R]", img: "https://www.govtrack.us/static/legislator-photos/412674-200px.jpeg", fav: false },
{us_state: "OH", vote: "No", party: "Republican", name: "Rep. Warren Davidson [R]", img: "https://www.govtrack.us/static/legislator-photos/412675-200px.jpeg", fav: false },
{us_state: "KY", vote: "No", party: "Republican", name: "Rep. James Comer [R]", img: "https://www.govtrack.us/static/legislator-photos/412676-200px.jpeg", fav: false },
{us_state: "AZ", vote: "No", party: "Republican", name: "Rep. Andy Biggs [R]", img: "https://www.govtrack.us/static/legislator-photos/412683-200px.jpeg", fav: false },
{us_state: "FL", vote: "No", party: "Republican", name: "Rep. Matt Gaetz [R]", img: "https://www.govtrack.us/static/legislator-photos/412690-200px.jpeg", fav: false },
{us_state: "FL", vote: "No", party: "Republican", name: "Rep. Neal Dunn [R]", img: "https://www.govtrack.us/static/legislator-photos/412691-200px.jpeg", fav: false },
{us_state: "FL", vote: "No", party: "Republican", name: "Rep. John Rutherford [R]", img: "https://www.govtrack.us/static/legislator-photos/412692-200px.jpeg", fav: false },
{us_state: "FL", vote: "No", party: "Republican", name: "Rep. Brian Mast [R]", img: "https://www.govtrack.us/static/legislator-photos/412698-200px.jpeg", fav: false },
{us_state: "FL", vote: "No", party: "Republican", name: "Rep. Francis Rooney [R]", img: "https://www.govtrack.us/static/legislator-photos/412699-200px.jpeg", fav: false },
{us_state: "GA", vote: "No", party: "Republican", name: "Rep. Drew Ferguson IV [R]", img: "https://www.govtrack.us/static/legislator-photos/412700-200px.jpeg", fav: false },
{us_state: "IN", vote: "No", party: "Republican", name: "Rep. Jim Banks [R]", img: "https://www.govtrack.us/static/legislator-photos/412702-200px.jpeg", fav: false },
{us_state: "IN", vote: "No", party: "Republican", name: "Rep. Trey Hollingsworth [R]", img: "https://www.govtrack.us/static/legislator-photos/412703-200px.jpeg", fav: false },
{us_state: "KS", vote: "No", party: "Republican", name: "Rep. Roger Marshall [R]", img: "https://www.govtrack.us/static/legislator-photos/412704-200px.jpeg", fav: false },
{us_state: "LA", vote: "No", party: "Republican", name: "Rep. Clay Higgins [R]", img: "https://www.govtrack.us/static/legislator-photos/412705-200px.jpeg", fav: false },
{us_state: "LA", vote: "Abstained", party: "Republican", name: "Rep. Mike Johnson [R]", img: "https://www.govtrack.us/static/legislator-photos/412706-200px.jpeg", fav: false },
{us_state: "MI", vote: "No", party: "Republican", name: "Rep. Jack Bergman [R]", img: "https://www.govtrack.us/static/legislator-photos/412709-200px.jpeg", fav: false },
{us_state: "MI", vote: "No", party: "Republican", name: "Rep. Paul Mitchell [R]", img: "https://www.govtrack.us/static/legislator-photos/412710-200px.jpeg", fav: false },
{us_state: "NC", vote: "No", party: "Republican", name: "Rep. Ted Budd [R]", img: "https://www.govtrack.us/static/legislator-photos/412712-200px.jpeg", fav: false },
{us_state: "NE", vote: "No", party: "Republican", name: "Rep. Don Bacon [R]", img: "https://www.govtrack.us/static/legislator-photos/412713-200px.jpeg", fav: false },
{us_state: "PA", vote: "Yes", party: "Republican", name: "Rep. Brian Fitzpatrick [R]", img: "https://www.govtrack.us/static/legislator-photos/412721-200px.jpeg", fav: false },
{us_state: "PA", vote: "Abstained", party: "Republican", name: "Rep. Lloyd Smucker [R]", img: "https://www.govtrack.us/static/legislator-photos/412722-200px.jpeg", fav: false },
{us_state: "TN", vote: "No", party: "Republican", name: "Rep. David Kustoff [R]", img: "https://www.govtrack.us/static/legislator-photos/412724-200px.jpeg", fav: false },
{us_state: "TX", vote: "No", party: "Republican", name: "Rep. Jodey Arrington [R]", img: "https://www.govtrack.us/static/legislator-photos/412726-200px.jpeg", fav: false },
{us_state: "WI", vote: "No", party: "Republican", name: "Rep. Mike Gallagher [R]", img: "https://www.govtrack.us/static/legislator-photos/412731-200px.jpeg", fav: false },
{us_state: "WY", vote: "No", party: "Republican", name: "Rep. Liz Cheney [R]", img: "https://www.govtrack.us/static/legislator-photos/412732-200px.jpeg", fav: false },
{us_state: "KS", vote: "No", party: "Republican", name: "Rep. Ron Estes [R]", img: "https://www.govtrack.us/static/legislator-photos/412735-200px.jpeg", fav: false },
{us_state: "MT", vote: "No", party: "Republican", name: "Rep. Greg Gianforte [R]", img: "https://www.govtrack.us/static/legislator-photos/412736-200px.jpeg", fav: false },
{us_state: "SC", vote: "No", party: "Republican", name: "Rep. Ralph Norman Jr. [R]", img: "https://www.govtrack.us/static/legislator-photos/412738-200px.jpeg", fav: false },
{us_state: "UT", vote: "No", party: "Republican", name: "Rep. John Curtis [R]", img: "https://www.govtrack.us/static/legislator-photos/412740-200px.jpeg", fav: false },
{us_state: "AZ", vote: "No", party: "Republican", name: "Rep. Debbie Lesko [R]", img: "https://www.govtrack.us/static/legislator-photos/412745-200px.jpeg", fav: false },
{us_state: "TX", vote: "No", party: "Republican", name: "Rep. Michael Cloud [R]", img: "https://www.govtrack.us/static/legislator-photos/412746-200px.jpeg", fav: false },
{us_state: "OH", vote: "No", party: "Republican", name: "Rep. Troy Balderson [R]", img: "https://www.govtrack.us/static/legislator-photos/412747-200px.jpeg", fav: false },
{us_state: "OK", vote: "No", party: "Republican", name: "Rep. Kevin Hern [R]", img: "https://www.govtrack.us/static/legislator-photos/412748-200px.jpeg", fav: false },
{us_state: "FL", vote: "No", party: "Republican", name: "Rep. Michael Waltz [R]", img: "https://www.govtrack.us/static/legislator-photos/412764-200px.jpeg", fav: false },
{us_state: "FL", vote: "No", party: "Republican", name: "Rep. Ross Spano [R]", img: "https://www.govtrack.us/static/legislator-photos/412765-200px.jpeg", fav: false },
{us_state: "FL", vote: "Abstained", party: "Republican", name: "Rep. Gregory Steube [R]", img: "https://www.govtrack.us/static/legislator-photos/412766-200px.jpeg", fav: false },
{us_state: "ID", vote: "No", party: "Republican", name: "Rep. Russ Fulcher [R]", img: "https://www.govtrack.us/static/legislator-photos/412773-200px.jpeg", fav: false },
{us_state: "IN", vote: "No", party: "Republican", name: "Rep. James Baird [R]", img: "https://www.govtrack.us/static/legislator-photos/412777-200px.jpeg", fav: false },
{us_state: "IN", vote: "No", party: "Republican", name: "Rep. Greg Pence [R]", img: "https://www.govtrack.us/static/legislator-photos/412778-200px.jpeg", fav: false },
{us_state: "KS", vote: "No", party: "Republican", name: "Rep. Steven Watkins [R]", img: "https://www.govtrack.us/static/legislator-photos/412779-200px.jpeg", fav: false },
{us_state: "MN", vote: "No", party: "Republican", name: "Rep. Jim Hagedorn [R]", img: "https://www.govtrack.us/static/legislator-photos/412788-200px.jpeg", fav: false },
{us_state: "MN", vote: "No", party: "Republican", name: "Rep. Pete Stauber [R]", img: "https://www.govtrack.us/static/legislator-photos/412792-200px.jpeg", fav: false },
{us_state: "MS", vote: "No", party: "Republican", name: "Rep. Michael Guest [R]", img: "https://www.govtrack.us/static/legislator-photos/412793-200px.jpeg", fav: false },
{us_state: "ND", vote: "No", party: "Republican", name: "Rep. Kelly Armstrong [R]", img: "https://www.govtrack.us/static/legislator-photos/412794-200px.jpeg", fav: false },
{us_state: "OH", vote: "No", party: "Republican", name: "Rep. Anthony Gonzalez [R]", img: "https://www.govtrack.us/static/legislator-photos/412807-200px.jpeg", fav: false },
{us_state: "PA", vote: "No", party: "Republican", name: "Rep. Daniel Meuser [R]", img: "https://www.govtrack.us/static/legislator-photos/412811-200px.jpeg", fav: false },
{us_state: "PA", vote: "No", party: "Republican", name: "Rep. John Joyce [R]", img: "https://www.govtrack.us/static/legislator-photos/412812-200px.jpeg", fav: false },
{us_state: "PA", vote: "No", party: "Republican", name: "Rep. Guy Reschenthaler [R]", img: "https://www.govtrack.us/static/legislator-photos/412813-200px.jpeg", fav: false },
{us_state: "SC", vote: "No", party: "Republican", name: "Rep. William Timmons [R]", img: "https://www.govtrack.us/static/legislator-photos/412815-200px.jpeg", fav: false },
{us_state: "SD", vote: "No", party: "Republican", name: "Rep. Dusty Johnson [R]", img: "https://www.govtrack.us/static/legislator-photos/412816-200px.jpeg", fav: false },
{us_state: "TN", vote: "Abstained", party: "Republican", name: "Rep. Tim Burchett [R]", img: "https://www.govtrack.us/static/legislator-photos/412817-200px.jpeg", fav: false },
{us_state: "TN", vote: "No", party: "Republican", name: "Rep. John Rose [R]", img: "https://www.govtrack.us/static/legislator-photos/412818-200px.jpeg", fav: false },
{us_state: "TN", vote: "No", party: "Republican", name: "Rep. Mark Green [R]", img: "https://www.govtrack.us/static/legislator-photos/412819-200px.jpeg", fav: false },
{us_state: "TX", vote: "No", party: "Republican", name: "Rep. Dan Crenshaw [R]", img: "https://www.govtrack.us/static/legislator-photos/412820-200px.jpeg", fav: false },
{us_state: "TX", vote: "No", party: "Republican", name: "Rep. Van Taylor [R]", img: "https://www.govtrack.us/static/legislator-photos/412821-200px.jpeg", fav: false },
{us_state: "TX", vote: "No", party: "Republican", name: "Rep. Lance Gooden [R]", img: "https://www.govtrack.us/static/legislator-photos/412822-200px.jpeg", fav: false },
{us_state: "TX", vote: "No", party: "Republican", name: "Rep. Ron Wright [R]", img: "https://www.govtrack.us/static/legislator-photos/412823-200px.jpeg", fav: false },
{us_state: "TX", vote: "No", party: "Republican", name: "Rep. Chip Roy [R]", img: "https://www.govtrack.us/static/legislator-photos/412826-200px.jpeg", fav: false },
{us_state: "VA", vote: "No", party: "Republican", name: "Rep. Denver Riggleman [R]", img: "https://www.govtrack.us/static/legislator-photos/412831-200px.jpeg", fav: false },
{us_state: "VA", vote: "No", party: "Republican", name: "Rep. Ben Cline [R]", img: "https://www.govtrack.us/static/legislator-photos/412832-200px.jpeg", fav: false },
{us_state: "WI", vote: "No", party: "Republican", name: "Rep. Bryan Steil [R]", img: "https://www.govtrack.us/static/legislator-photos/412836-200px.jpeg", fav: false },
];

class App extends Component {
  render() {
    return (
      <div className="App">
         <FilteredList items={people} />
      </div>
    );
  }
}

// We used the functions below to print a csv file
// in our console to get all the representatives' information.

// import Csv from "./congress_votes_equality_act.csv";
// $(document).ready(function() {
//     $.ajax({
//         type: "GET",
//         url: Csv,
//         dataType: "text",
//         success: function(data) {
//             // alert(data);
//             // console.log("HELLO" + data);
//             processData(data);}
//     });
// });
//
// var people = []
//
// function processData(allText) {
//     let people = []
//   var allTextLines = allText.split(/\r\n|\n/);
//
//   for (var i = 1; i< allTextLines.length-1; i++){
//     var tmp = allTextLines[i].split(',');
//     var vote = tmp[3];
//     if (vote === 'Aye'){
//         vote = 'Yes'
//     } else if (vote == 'Not Voting'){
//         vote = 'Abstained'
//     }
//     var person = {
//       us_state: tmp[1],
//       vote: vote,
//       party: tmp[5],
//       name: tmp[4],
//       img: "https://www.govtrack.us/static/legislator-photos/" + tmp[0] + "-200px.jpeg",
//       fav: false,
//     };
//     people.push(person);
//     console.log(person);
//   }
//
// }


export default App;
